let shopItemsData = [
    {
    id: "book_31301",
    name: "کتاب ۱۹۸۴",
    price: "۷۵۰۰۰",
    desc: "کتاب ۱۹۸۴ اثر جورج اورول نشر شاهدخت پاییز",
    img: "images/img-1.jpg",
  },
  {
    id: "book_31302",
    name: "کتاب شدن",
    price: "۶۳۰۰۰",
    desc: "کتاب شدن اثر میشل اوباما، رومان و زندگی نامه",
    img: "images/img-2.jpg",
  },
  {
    id: "book_31303",
    name: "کتاب فقط ساکت شوانجامش بده",
    price: "۹۴۰۰۰",
    desc: "کتاب فقط ساکت شو و انجامش بده اثر برایان تریسی",
    img: "images/img-3.jpg",
  },
  {
    id: "book_31304",
    name: "کتاب نبرد من",
    price: "۵۵۰۰۰",
    desc: " کتاب نبرد من اثر آدولف هتلر، تاریخ و سیاست",
    img: "images/img-4.jpg",
  },
  {
    id: "book_31305",
    name: "کتاب جهانی که می بینم",
    price: "۹۰۰۰۰",
    desc: "کتاب جهانی که می بینم، اثر آلبرت انیشتین با موضوع علمی",
    img: "images/img-5.jpg",
  },
  {
    id: "book_31306",
    name: "کتاب جنایت و مکافات",
    price: "۳۴۰۰۰",
    desc: "کتاب جنایت و مکافات اثر فئودور داستایوفسکی، رمان",
    img: "images/img-6.jpg",
  },
  {
    id: "book_31307",
    name: "کتاب شرمنده نباش دختر",
    price: "۴۹۰۰۰",
    desc: "کتاب شرمنده نباش دختر اثر ریچل هالیس نشر کتاب کوله پشتی",
    img: "images/img-7.png",
  },
  {
    id: "book_31308",
    name: "polo shirt",
    price: 45,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-8.png",
  },
  {
    id: "book_31309",
    name: "denim shirt",
    price: 85,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-9.png",
  },
  {
    id: "book_31310",
    name: "denim pants",
    price: 120,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-10.png",
  },
  {
    id: "book_31311",
    name: "basic cap",
    price: 35,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-11.png",
  },
  {
    id: "book_31312",
    name: "leather boots",
    price: 350,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-12.png",
  },
];